### ISSUE TITLE
Conflicting file in Dropbox when uploading changed file from local

### ISSUE THREAD

**Issue by yuriytkach** [yuriytkach/dsync-client#12]
When file changes locally and we try to upload it, we get exception 
com.dropbox.core.v2.files.UploadErrorException: Exception in upload: {".tag":"path","reason":{".tag":"conflict","conflict":"file"},"upload_session_id":"ssss"}

**Comment by eduardoribeiro17** [comment]
You solved this?

**Comment by ytkach** [comment]
Hello. Yes, I solved it in the commit: c530898
Does it appears again for you?
